[debug]
#address = "localhost"
#port = 8000
#workers = [number of cpus * 2]
#keep_alive = 5
#read_timeout = 5
#write_timeout = 5
log_level = "normal"
#secret_key = [randomly generated at launch]
#limits = { forms = 32768 }

